import {
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatFormFieldModule,
    MatSelectModule,
    MatDatepickerModule,       
    MatNativeDateModule,
    MatProgressBarModule,
    MatDialogModule,
    MatCheckboxModule,
    MatInputModule,
    MatButtonToggleModule,
    MatTreeModule,
    MatTooltipModule,
    MatChipsModule

} from '@angular/material';
import { NgModule } from '@angular/core';

@NgModule({
    imports: [
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        MatIconModule,
        MatListModule,
        MatGridListModule,
        MatCardModule,
        MatMenuModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatTabsModule,
        MatSlideToggleModule,
        MatFormFieldModule,
        MatSelectModule,
        MatDatepickerModule,       
        MatNativeDateModule,
        MatProgressBarModule,
        MatDialogModule,
        MatCheckboxModule,
        MatInputModule,
        MatButtonToggleModule,
        MatTreeModule,
        MatTooltipModule,
        MatChipsModule
    ],

    exports: [
        MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,
        MatIconModule,
        MatListModule,
        MatGridListModule,
        MatCardModule,
        MatMenuModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatTabsModule,
        MatSlideToggleModule,
        MatFormFieldModule,
        MatSelectModule,
        MatDatepickerModule,       
        MatNativeDateModule,
        MatProgressBarModule,
        MatDialogModule,
        MatCheckboxModule,
        MatInputModule,
        MatButtonToggleModule,
        MatTreeModule,
        MatTooltipModule,
        MatChipsModule
    ],
})
export class CustomMaterialModule { }